apiVersion: gate.v3.haproxy.org/v3
kind: HugConf
metadata:
  name: hugconf
  namespace: haproxy-unified-gateway
spec:
  logging:
    defaultLevel: "Info"
    categoryLevelList:
      - category: "k8s"
        level: "Error"
      - category: "gate"
        level: "Info"
      - category: "status"
        level: "Info"
      - category: "batch"
        level: "Error"
      - category: "app"
        level: "Info"
      - category: "certs-storage"
        level: "Info"
      - category: "hugservice"
        level: "Info"
      - category: "status"
        level: "Debug"
  globalRef:
    group: gate.v3.haproxy.org
    kind: Global
    name: global
    namespace: haproxy-unified-gateway
