mode: commit
min_length: 3
allowed:
  - acl
  - backend
  - backends
  - balancer
  - betteralign
  - categorizer
  - cfg
  - config
  - crd
  - crt
  - crtlistfiles
  - crtlists
  - endpointslices
  - env
  - entreprise
  - entrypoint
  - envtest
  - failsafe
  - forwardfor
  - frontend
  - frontends
  - gatewayclass
  - github
  - gitignore
  - gitlab
  - golang
  - golangci
  - groups
  - haproxycfg
  - haproxytech
  - huggate
  - hugconf
  - hugservice
  - http
  - httproute
  - https
  - hostnames
  - init
  - ipv
  - json
  - keymap
  - kubebuilder
  - kubeconfig
  - leaderelection
  - lifecycle
  - linter
  - linters
  - loadbalancer
  - lua
  - maxconn
  - maxsslconn
  - memmax
  - mkdir
  - modfile
  - mutex
  - namespace
  - namespaces
  - parallelize
  - passthrough
  - pid
  - pidfile
  - rbac
  - readme
  - reconciler
  - releaser
  - repo
  - req
  - resync
  - runtime
  - slogger
  - ssl
  - sslv
  - sudo
  - symlink
  - taskfile
  - testenv
  - tcp
  - tls
  - tlsv
  - todo
  - ubuntu
  - unix
  - usr
  - utils
  - workdir
  - yaml
  - kubectl
  - hostname
  - dereference
  - darwin
  - performant
  - dockerhub
  - SNI
  - optim
  - gzip
  - gwapi
  - prometheus
  - apiextensions
  - clientset
  - unmarshaled
  - kubernetes
  - amd
  - buildx
  - misconfiguration
  - upsert
  - upserted
  - CEL
  - httpfilters
  - allowlist
  - inttest
  - regsub
  - backreference
  - backreferences
  - iowriter
