stages:
  - bots
  - diff
  - lint
  - security
  - build
  - unit-tests
  - conformance-tests
  - metrics-report
variables:
  HAPROXY_VERSION: "3.2"
  KIND: v0.27.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GO_VERSION: "1.26"
  DOCKER_VERSION: "28.1"
  JUNIT_FILE: "junit-report.xml"
  GOTESTSUM_JUNITFILE: "junit-report.xml"
  HAPROXY_REGISTRY_GO: "registry.haproxy.com/gophers"
  METRICS_SAMPLE_ENABLED: "1"
  METRICS_SAMPLE_INTERVAL: "2"
  METRICS_OUTPUT_DIR: "${CI_PROJECT_DIR}/metrics-output"

include:
  - local: .gitlab/bots.yml
  - local: .gitlab/diff.yml
  - local: .gitlab/lint.yml
  - local: .gitlab/security.yml
  - local: .gitlab/build.yaml
  - local: .gitlab/unit-tests.yml
  - local: .gitlab/conformance-tests.yml
  - local: .gitlab/metrics-report.yml
