#https://taskfile.dev/
version: "3"

dotenv:
  - .env

includes:
  vars:
    taskfile: taskfile/.vars.yml
    flatten: true
  tools:
    taskfile: taskfile/.tools.yml
    flatten: true
  k0s:
    taskfile: taskfile/k0s.yml
    flatten: true
  kind:
    taskfile: taskfile/kind.yml
    flatten: true
  kubectl:
    taskfile: taskfile/kubectl.yml
    flatten: true
  git:
    taskfile: taskfile/git.yml
    flatten: true
  generate:
    taskfile: taskfile/generate.yml
    flatten: true
  go-tools:
    taskfile: taskfile/go-tools.yml
    flatten: true
  controller-gen:
    taskfile: taskfile/controller-gen.yml
    flatten: true
  conformance:
    taskfile: taskfile/conformance.yml
    flatten: true

vars:

tasks:
  ci:
    desc: "do almost all the checks"
    cmds:
      - task: check-commit
      - task: tidy
      - task: format
      - task: generate
      - task: controller-gen
      - task: lint
      - task: test

  test-todo:
    desc: "run Go tests"
    cmds:
      - task: test
        vars:
          TEST_TAGS: "test_todo"

  test:
    desc: "run Go tests"
    deps:
      - task: check-go-tool
        vars:
          TOOL: GOTESTSUM
    vars:
      TOOL: envtest
      PKG: '{{default "./..." .PKG}}'
      FORMAT: '{{default "testdox" .FORMAT}}'
      POD_IP: "1.2.3.4"
      POD_NAME: "hug-7469984948-qgnfw"
      POD_NAMESPACE: "hug"
      HAPROXY_BIN: '{{or (env "HAPROXY_BIN") "/usr/local/sbin/haproxy"}}'
    cmds:
      - |
        KUBEBUILDER_ASSETS=/{{.TMP}}/{{.TOOL}} \
        ENVTEST_VERSION={{.ENVTEST_VERSION}} \
        POD_IP={{.POD_IP}} \
        POD_NAME={{.POD_NAME}} \
        POD_NAMESPACE={{.POD_NAMESPACE}} \
        HAPROXY_BIN={{.HAPROXY_BIN}} \
        POD_IP=$POD_IP POD_NAME=$POD_NAME POD_NAMESPACE=$POD_NAMESPACE ENVTEST_VERSION=$ENVTEST_VERSION KUBEBUILDER_ASSETS=$KUBEBUILDER_ASSETS HAPROXY_BIN=$HAPROXY_BIN \
        /{{.TMP}}/gotestsum/{{.GOTESTSUM_VERSION}}/gotestsum \
          --format-icons=hivis \
          --format={{.FORMAT}} \
          --format-hide-empty-pkg \
          -- -count=1 \
            -tags="{{.TEST_TAGS}}" \
            -v \
            {{.PKG}}
  tidy:
    desc: "run Go mod tidy"
    cmds:
      - go mod tidy

  lint:
    desc: "run Go linters"
    deps:
      - task: check-go-tools
        vars:
          TOOLS: [BETTERALIGN, REVIVE, STATICCHECK]
    cmds:
      - /{{.TMP}}/revive/{{.REVIVE_VERSION}}/revive -config revive.toml -formatter friendly -set_exit_status ./...
      - /{{.TMP}}/staticcheck/{{.STATICCHECK_VERSION}}/staticcheck ./...
      - /{{.TMP}}/betteralign/{{.BETTERALIGN_VERSION}}/betteralign ./...

  format:
    desc: "formats the code"
    deps:
      - task: check-go-tools
        vars:
          TOOLS: [BETTERALIGN, GOFUMPT]
    cmds:
      - go fix ./...
      - /{{.TMP}}/betteralign/{{.BETTERALIGN_VERSION}}/betteralign -apply ./... || true
      - /{{.TMP}}/gofumpt/{{.GOFUMPT_VERSION}}/gofumpt -l -w .
      - go run cmd/crd-version-check/main.go

  licenses:
    dir: cmd/controller
    desc: "check licenses"
    deps:
      - task: check-go-tool
        vars:
          TOOL: GO_LICENSES
    cmds:
      - |
        PROJECT="$(go list -m)"
        ALLOWED_LICENSES="$(<../../.allowed_license_types)"
        /{{.TMP}}/go-licenses/{{.GO_LICENSES_VERSION}}/go-licenses report --ignore "$PROJECT" --ignore "github.com/modern-go/reflect2" --ignore "golang.org/x/sys" --ignore "golang.org/x/sys/unix"  .
        /{{.TMP}}/go-licenses/{{.GO_LICENSES_VERSION}}/go-licenses check --allowed_licenses="$ALLOWED_LICENSES" --ignore "$PROJECT"  --ignore "github.com/modern-go/reflect2" --ignore "github.com/modern-go/reflect2" --ignore "golang.org/x/sys/unix"  .

  check-commit:
    deps:
      - task: check-go-tool
        vars:
          TOOL: CHECK_COMMIT
    cmds:
      - /{{.TMP}}/check-commit/{{.CHECK_COMMIT_VERSION}}/check-commit

  govulncheck:
    deps:
      - task: check-go-tool
        vars:
          TOOL: GOVULNCHECK
    cmds:
      - /{{.TMP}}/govulncheck/{{.GOVULNCHECK_VERSION}}/govulncheck -show verbose ./...

  legal:
    desc: "check legal"
    cmds:
      - task: govulncheck
      - task: licenses

  controller-gen:
    cmds:
      - task: controller-gen-deep-copy
      - task: controller-gen-manifest
