// Copyright 2025 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//revive:disable:unhandled-error
package main

import (
	"fmt"
	"html"
	"os"
	"slices"
	"strings"
)

const (
	svgWidth   = 900
	svgHeight  = 260
	svgPadL    = 60
	svgPadR    = 20
	svgPadT    = 20
	svgPadB    = 40
	svgLegendH = 22
)

// svgPalette mirrors the PNG palette so colors stay consistent.
var svgPalette = []string{
	"#2563eb", "#dc2626", "#16a34a", "#a855f7",
	"#ea580c", "#0ea5e9", "#a16207", "#db2777",
}

// renderHTMLReport writes a single-page self-contained HTML with inline SVG
// charts for every (suite, metric, job) combination. comparisonHTML, if
// non-empty, is embedded near the top as a pre-formatted HTML block.
func renderHTMLReport(jobs []jobData, outputDir, comparisonHTML string) (string, error) {
	suiteSet := make(map[string]struct{})
	for _, job := range jobs {
		for _, suite := range job.Suites {
			suiteSet[suite.Name] = struct{}{}
		}
	}
	suiteNames := make([]string, 0, len(suiteSet))
	for name := range suiteSet {
		suiteNames = append(suiteNames, name)
	}
	slices.Sort(suiteNames)

	jobSuiteMap := make(map[string]map[string][]metricsSample)
	for _, job := range jobs {
		jobSuiteMap[job.Name] = make(map[string][]metricsSample)
		for _, suite := range job.Suites {
			jobSuiteMap[job.Name][suite.Name] = suite.Samples
		}
	}

	var b strings.Builder
	writeHTMLHeader(&b)

	if comparisonHTML != "" {
		b.WriteString(comparisonHTML)
	}

	for _, suiteName := range suiteNames {
		writeHTMLSuite(&b, suiteName, jobs, jobSuiteMap)
	}

	writeHTMLFooter(&b)

	path := outputDir + "/metrics-report.html"
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("writing HTML report: %w", err)
	}
	return path, nil
}

func writeHTMLHeader(b *strings.Builder) {
	b.WriteString(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>HUG Integration Test Metrics</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, -apple-system, Segoe UI, Helvetica, Arial, sans-serif;
         max-width: 1100px; margin: 2rem auto; padding: 0 1rem; line-height: 1.4; }
  h1 { font-size: 1.5rem; }
  h2 { font-size: 1.2rem; border-bottom: 1px solid #ddd; padding-bottom: .25rem; }
  h3 { font-size: 1rem; margin-top: 1.25rem; }
  details { margin: 1rem 0; }
  summary { font-weight: 600; cursor: pointer; padding: .25rem 0; }
  table { border-collapse: collapse; margin: .25rem 0 .75rem; font-size: .85rem; }
  th, td { border: 1px solid #ccc; padding: .2rem .5rem; text-align: right; }
  th:first-child, td:first-child { text-align: left; }
  .chart { display: block; margin: .25rem 0 1rem; max-width: 100%; height: auto; }
  .job-block { margin: .75rem 0 1.25rem; }
  table.cmp { font-size: .9rem; }
  table.cmp td, table.cmp th { color: #111; background: #fff; }
  tr.status-worse td { background: #fde2e2; }
  tr.status-better td { background: #e3f5e1; }
  tr.status-new td { background: #fff4d6; }
  footer { color: #888; font-size: .8rem; margin-top: 2rem; }
</style>
</head>
<body>
<h1>HUG Integration Test Metrics</h1>
`)
}

func writeHTMLFooter(b *strings.Builder) {
	b.WriteString("<footer>Generated by HUG metrics-report</footer>\n</body>\n</html>\n")
}

func writeHTMLSuite(
	b *strings.Builder, suiteName string,
	jobs []jobData, jobSuiteMap map[string]map[string][]metricsSample,
) {
	hasAny := false
	for _, job := range jobs {
		if len(jobSuiteMap[job.Name][suiteName]) > 0 {
			hasAny = true
			break
		}
	}
	if !hasAny {
		return
	}

	fmt.Fprintf(b, "<details open><summary>%s</summary>\n", html.EscapeString(suiteName))

	for _, tracked := range trackedMetrics {
		unitLabel := ""
		if tracked.Unit != "" {
			unitLabel = " (" + tracked.Unit + ")"
		}

		var sections []string
		for _, job := range jobs {
			samples := jobSuiteMap[job.Name][suiteName]
			if len(samples) == 0 {
				continue
			}
			series := buildTestSeries(samples, tracked.Key, tracked.Unit)
			if len(series) == 0 {
				continue
			}
			sections = append(sections, renderJobBlock(job.Name, suiteName, series))
		}
		if len(sections) == 0 {
			continue
		}

		fmt.Fprintf(b, "<h3>%s%s</h3>\n", html.EscapeString(tracked.Title), html.EscapeString(unitLabel))
		for _, s := range sections {
			b.WriteString(s)
		}
	}

	b.WriteString("</details>\n")
}

func renderJobBlock(jobName, suiteName string, series []testTimeSeries) string {
	var b strings.Builder
	fmt.Fprintf(&b, `<div class="job-block"><strong>%s</strong>`, html.EscapeString(jobName))

	b.WriteString(`<table><thead><tr><th>Test</th><th>Min</th><th>Max</th><th>Final</th></tr></thead><tbody>`)
	for _, ts := range series {
		minV, maxV, lastV := stats(ts.Values)
		fmt.Fprintf(&b, "<tr><td>%s</td><td>%.2f</td><td>%.2f</td><td>%.2f</td></tr>",
			html.EscapeString(shortTestName(ts.Test, suiteName)), minV, maxV, lastV)
	}
	b.WriteString("</tbody></table>")

	b.WriteString(renderSVG(series, suiteName))
	b.WriteString("</div>\n")
	return b.String()
}

// renderSVG produces a self-contained inline SVG element with line series and a legend.
func renderSVG(series []testTimeSeries, suiteName string) string {
	if len(series) == 0 {
		return ""
	}

	var allValues []float64
	maxElapsed := 0.0
	for _, ts := range series {
		allValues = append(allValues, ts.Values...)
		if len(ts.Times) > 0 {
			if last := ts.Times[len(ts.Times)-1]; last > maxElapsed {
				maxElapsed = last
			}
		}
	}
	if len(allValues) < 2 {
		return ""
	}
	if maxElapsed == 0 {
		maxElapsed = 1
	}

	minV, maxV, _ := stats(allValues)
	vRange := maxV - minV
	if vRange == 0 {
		vRange = 1
	}
	minV -= vRange * 0.05
	maxV += vRange * 0.05
	if minV < 0 {
		minV = 0
	}

	plotW := float64(svgWidth - svgPadL - svgPadR)
	plotH := float64(svgHeight - svgPadT - svgPadB)
	legendRows := (len(series) + 2) / 3
	totalH := svgHeight + legendRows*svgLegendH

	scaleX := func(t float64) float64 { return float64(svgPadL) + (t/maxElapsed)*plotW }
	scaleY := func(v float64) float64 { return float64(svgPadT) + plotH - (v-minV)/(maxV-minV)*plotH }

	var b strings.Builder
	fmt.Fprintf(&b,
		`<svg class="chart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" role="img" aria-label="chart">`,
		svgWidth, totalH)
	b.WriteString(`<rect width="100%" height="100%" fill="#fafafa"/>`)
	writeSVGAxes(&b, plotW, plotH, minV, maxV, maxElapsed)

	// Series polylines
	for i, ts := range series {
		color := svgPalette[i%len(svgPalette)]
		var pts strings.Builder
		for j := range ts.Times {
			if j > 0 {
				pts.WriteByte(' ')
			}
			fmt.Fprintf(&pts, "%.1f,%.1f", scaleX(ts.Times[j]), scaleY(ts.Values[j]))
		}
		fmt.Fprintf(&b,
			`<polyline fill="none" stroke="%s" stroke-width="1.8" points="%s"/>`,
			color, pts.String())
	}

	writeSVGLegend(&b, series, suiteName)
	b.WriteString("</svg>")
	return b.String()
}

func writeSVGAxes(b *strings.Builder, plotW, plotH, minV, maxV, maxElapsed float64) {
	for i := range 6 {
		frac := float64(i) / 5
		y := float64(svgPadT) + plotH*frac
		fmt.Fprintf(b,
			`<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#dcdcdc"/>`,
			float64(svgPadL), y, float64(svgWidth-svgPadR), y)
		val := minV + (1-frac)*(maxV-minV)
		fmt.Fprintf(b,
			`<text x="%d" y="%.1f" font-family="monospace" font-size="10" fill="#666" text-anchor="end">%s</text>`,
			svgPadL-4, y+3, html.EscapeString(formatAxisValue(val)))
	}
	fmt.Fprintf(b,
		`<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#999"/>`,
		svgPadL, svgPadT, svgPadL, svgPadT+int(plotH))
	fmt.Fprintf(b,
		`<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#999"/>`,
		svgPadL, svgPadT+int(plotH), svgWidth-svgPadR, svgPadT+int(plotH))

	for i := range 6 {
		frac := float64(i) / 5
		t := frac * maxElapsed
		x := float64(svgPadL) + frac*plotW
		fmt.Fprintf(b,
			`<text x="%.1f" y="%d" font-family="monospace" font-size="10" fill="#666" text-anchor="middle">%.0fs</text>`,
			x, svgPadT+int(plotH)+14, t)
	}
}

func writeSVGLegend(b *strings.Builder, series []testTimeSeries, suiteName string) {
	legendColW := (svgWidth - svgPadL) / 3
	for i, ts := range series {
		col := i % 3
		row := i / 3
		x := svgPadL + col*legendColW
		y := svgHeight + row*svgLegendH + 12
		color := svgPalette[i%len(svgPalette)]
		fmt.Fprintf(b,
			`<rect x="%d" y="%d" width="14" height="4" fill="%s"/>`,
			x, y-3, color)
		fmt.Fprintf(b,
			`<text x="%d" y="%d" font-family="system-ui,sans-serif" font-size="11" fill="#333">%s</text>`,
			x+18, y+1, html.EscapeString(shortTestName(ts.Test, suiteName)))
	}
}
