apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  apiServerAddress: "0.0.0.0"
  apiServerPort: 7443
kind: Cluster
nodes:
  - role: control-plane

    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      controllerManager:
          extraArgs:
            max-endpoints-per-slice: "5"
            node-cidr-mask-size-ipv4: "21"
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      metadata:
              name: config
      maxPods: 2048
