// Copyright 2025 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

//revive:disable:unhandled-error

import (
	"fmt"
	"os"
	"strings"

	"github.com/google/renameio"
	"github.com/phuslu/log"
	"gopkg.in/yaml.v3"
)

type SupportVersion struct {
	Version string   `yaml:"version"`
	GA      string   `yaml:"ga"`
	MinEOL  string   `yaml:"min_eol"`
	GwAPI   []string `yaml:"gw_api"`
}

type Support struct {
	Versions []*SupportVersion `yaml:"versions"`
}

func generateLifecycle() {
	yamlFile, err := os.ReadFile("../../documentation/lifecycle.yaml")
	if err != nil {
		log.Error().Err(err).Msg("failed to read lifecycle.yaml")
		return
	}
	var support Support
	err = yaml.Unmarshal(yamlFile, &support)
	if err != nil {
		log.Panic().Err(err).Msg("failed to unmarshal lifecycle.yaml")
	}

	var buff strings.Builder
	buff.WriteString(`# ![HAProxy](../assets/images/haproxy-weblogo-210x49.png "HAProxy")`)
	buff.WriteRune('\n')
	buff.WriteRune('\n')
	buff.WriteString(`### Lifecycle`)
	buff.WriteRune('\n')
	buff.WriteRune('\n')
	buff.WriteString(`| Version | GA | EOL | Gateway API versions |`)
	buff.WriteRune('\n')
	buff.WriteString(`| -:|:-:|:-:|:-:|`)
	buff.WriteRune('\n')

	for _, version := range support.Versions {
		buff.WriteString(fmt.Sprintf(`| **%s** | %s | %s | %s |`, version.Version, version.GA, version.MinEOL, strings.Join(version.GwAPI, ", ")))
		buff.WriteRune('\n')
	}

	buff.WriteRune('\n')
	buff.WriteString(`This is autogenerated from [lifecycle.yaml](lifecycle.yaml), do not edit manually.`)
	buff.WriteRune('\n')

	err = renameio.WriteFile("../../documentation/lifecycle.md", []byte(buff.String()), 0o644)
	if err != nil {
		log.Error().Err(err).Msg("failed to write lifecycle.md")
	}
}
